### ISSUE TITLE
Upgrade to jsonwebtoken 9.0.0

### ISSUE THREAD

**Issue by fabge** [MarioArnt/azure-ad-jwt-lite#31]
Hello,
any chance, the package will be updated to use [jsonwebtoken 9.0.0](https://github.com/auth0/node-jsonwebtoken/wiki/Migration-Notes:-v8-to-v9) in the near future?
The current version shows a critical vulnerarbility regarding `jwt.verify()`

Dependabot has already created a [PR](https://github.com/MarioArnt/azure-ad-jwt-lite/pull/29) with the proposed changes. A test fails though as unverified `verify()` calls are forbidden since 9.0.0. 

Thank you!

**Comment by MarioArnt** [comment]
Hi,

Thanks for reporting this :)

The issue was solved with #32
