### ISSUE TITLE
Caching of public keys

### ISSUE THREAD

**Issue by tatejones** [MarioArnt/azure-ad-jwt-lite#7]
Hi,

Are there any plans to cache the Microsoft public keys with an option to expiry/rotate them?  It just seems expensive to retrieve the keys for every authentication call.

Cheers

**Comment by MarioArnt** [comment]
Hi @tatejones 

Very good point, I used this in a FaaS context so caching does not apply in my use case
However it can be very useful for others and save a lot of unnecessary API calls

Caching keys should be default IMO with an default cache duration that can be overwritten by options

Do you want to implement this ?
